apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-service
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80     # targets any pod running on port 80
      #targetPort: 80   #referring to containerPort
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: test.api
        ports:
        - containerPort: 80  #expose port 80